version: "3.8"

services:
  web:
    build: .
    ports:
      - "8003:8000" # 外部ポートを8003に変更
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-docker-dev-key
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shiftmaster_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"

volumes:
  postgres_data:
