# Generated by Django 5.2 on 2025-06-26 08:05

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='シフト名')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('break_time', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='休憩時間')),
                ('color_code', models.CharField(default='#007bff', max_length=7, verbose_name='表示色')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'シフトタイプ',
                'verbose_name_plural': 'シフトタイプ',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='従業員ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('position', models.CharField(max_length=100, verbose_name='職種')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='入社日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='プロフィール画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '従業員',
                'verbose_name_plural': '従業員',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField(verbose_name='シフト日')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('completed', '完了')], default='pending', max_length=10, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='実際の開始時間')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='実際の終了時間')),
                ('break_duration', models.DurationField(blank=True, null=True, verbose_name='実際の休憩時間')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='残業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to='shifts.employee', verbose_name='承認者')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.employee', verbose_name='従業員')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_shifts', to='shifts.employee', verbose_name='申請者')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shifttype', verbose_name='シフトタイプ')),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト',
                'ordering': ['-shift_date', 'employee__employee_id'],
                'unique_together': {('employee', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='チェックイン時間')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='チェックアウト時間')),
                ('break_start_time', models.DateTimeField(blank=True, null=True, verbose_name='休憩開始時間')),
                ('break_end_time', models.DateTimeField(blank=True, null=True, verbose_name='休憩終了時間')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='勤務場所')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='shifts.shift', verbose_name='シフト')),
            ],
            options={
                'verbose_name': '出勤記録',
                'verbose_name_plural': '出勤記録',
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('change', 'シフト変更'), ('swap', 'シフト交換'), ('cancel', 'シフト取消'), ('overtime', '残業申請')], max_length=10, verbose_name='申請タイプ')),
                ('reason', models.TextField(verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('completed', '完了')], default='pending', max_length=10, verbose_name='ステータス')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理者メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='shifts.shift', verbose_name='元のシフト')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='shifts.employee', verbose_name='申請者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='shifts.employee', verbose_name='承認者')),
                ('swap_with_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='shifts.employee', verbose_name='交換相手')),
                ('new_shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.shifttype', verbose_name='新しいシフトタイプ')),
            ],
            options={
                'verbose_name': 'シフト申請',
                'verbose_name_plural': 'シフト申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('notification_type', models.CharField(choices=[('shift_assigned', 'シフト割当'), ('shift_changed', 'シフト変更'), ('request_approved', '申請承認'), ('request_rejected', '申請却下'), ('reminder', 'リマインダー'), ('announcement', 'お知らせ')], max_length=20, verbose_name='通知タイプ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.employee', verbose_name='受信者')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.shift', verbose_name='関連シフト')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.shiftrequest', verbose_name='関連申請')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
