# Generated by Django 5.2 on 2025-04-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('weekly', '週次'), ('monthly', '月次'), ('ad_hoc', '臨時')], max_length=50)),
                ('weekday', models.CharField(blank=True, max_length=10, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialysisPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dialysis_time', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DialysisStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shift_type', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('remarks_am', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks_pm', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('email', 'メール'), ('line', 'LINE')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('土', '土曜日'), ('日', '日曜日')], max_length=10, unique=True)),
                ('nurse_required', models.IntegerField(default=0, verbose_name='看護師必要人数')),
                ('engineer_required', models.IntegerField(default=0, verbose_name='臨床工学技士必要人数')),
                ('assistant_required', models.IntegerField(default=0, verbose_name='看護補助必要人数')),
                ('total_required', models.IntegerField(default=0, verbose_name='必要合計人数')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kana', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(max_length=100)),
                ('assigned_locations', models.JSONField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('work_constraints', models.JSONField(blank=True, null=True)),
                ('qualifications', models.JSONField(blank=True, null=True)),
                ('work_details', models.JSONField()),
                ('committees', models.JSONField(blank=True, null=True)),
                ('teams', models.JSONField(blank=True, null=True)),
                ('clinical_ladder', models.CharField(blank=True, max_length=10, null=True)),
                ('yearly_goals', models.TextField(blank=True, null=True)),
                ('career_history', models.TextField(blank=True, null=True)),
                ('ability_rating', models.JSONField(blank=True, null=True)),
                ('performance_evaluation', models.JSONField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('interview_history', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_notify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('paid', '有給休暇'), ('substitute', '振替休暇'), ('weekend', '週末休暇'), ('summer', '夏季休暇'), ('special', '特別休暇'), ('exemption', '免除休暇')], max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave', models.FloatField(default=0)),
                ('compensatory_leave', models.FloatField(default=0)),
                ('weekend_leave', models.FloatField(default=0)),
                ('night_shift_leave', models.FloatField(default=0)),
                ('max_annual_leave', models.FloatField(default=40)),
                ('goal_annual_leave', models.FloatField(default=20)),
                ('admin_only', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='shifts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OnCallShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('shift_type', models.CharField(choices=[('night', '夜間呼出'), ('weekend', '週末呼出')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', '午前'), ('afternoon', '午後'), ('night', '夜勤')], default='morning', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', '午前'), ('afternoon', '午後'), ('night', '夜勤')], max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
            ],
        ),
    ]
