# Generated by Django 5.2 on 2025-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftrequirement',
            options={'verbose_name': 'シフト要件', 'verbose_name_plural': 'シフト要件'},
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', '月曜日'), ('Tuesday', '火曜日'), ('Wednesday', '水曜日'), ('Thursday', '木曜日'), ('Friday', '金曜日'), ('Saturday', '土曜日'), ('Sunday', '日曜日')], max_length=10, unique=True),
        ),
    ]
