# Generated by Django 5.2 on 2025-06-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_shiftrequirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
    ]
