# Generated by Django 5.2 on 2025-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='assistant_required',
            field=models.IntegerField(default=0, verbose_name='看護補助必要人数'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='day_of_week',
            field=models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('土', '土曜日'), ('日', '日曜日')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='engineer_required',
            field=models.IntegerField(default=0, verbose_name='臨床工学技士必要人数'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='nurse_required',
            field=models.IntegerField(default=0, verbose_name='看護師必要人数'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='total_required',
            field=models.IntegerField(default=0, verbose_name='必要合計人数'),
        ),
    ]
